### ISSUE TITLE
Add latency check on ping command.

### ISSUE THREAD

**Issue by firtysh** [firtysh/mlody#1]
Bot replies with ' pong! ' on ping command as response. Change it so it responds with api latency and bot latency.
Example  : Bot latency is 300ms & API latency is 150ms.

**Comment by SHAIKASIFALI** [comment]
Hello I would like to work on this issue under the #jwoc 2k23 can u please assign me this issue ..

**Comment by firtysh** [comment]
> Hello I would like to work on this issue under the #jwoc 2k23 can u please assign me this issue ..

@SHAIKASIFALI  Assigned

**Comment by RAOdotSH** [comment]
May I try my hands on this issue?

**Comment by firtysh** [comment]
> May I try my hands on this issue?

This one is already assigned but you can try other issues or you can create one

**Comment by RAOdotSH** [comment]
Ok!
