### ISSUE TITLE
add queue list 

### ISSUE THREAD

**Issue by ashavijit** [firtysh/mlody#2]
Add queue list to show to upcoming song by order.

**Comment by sajdakabir** [comment]
can I work on this issue?

**Comment by firtysh** [comment]
> can I work on this issue?

Absolutely you can. But as per JWOC guidelines any comment or contribution before 15th feb will be considered invalid.

**Comment by SHAIKASIFALI** [comment]
I would love to work on this issue can you please assign me this issue #jwoc 2k23

**Comment by RAOdotSH** [comment]
I would love to work on this issue.

**Comment by firtysh** [comment]
> I would love to work on this issue.

Assigned
